### ISSUE TITLE
Sentiment Analysis Twitter Bahasa Indonesia dengan TextBlob

### ISSUE THREAD

**Issue by IanNarsa** [Ahtuz/sentiment-analysis-indo#1]
Mas kyaknya kalau analisis sentimen bahasa Indonesia  pakai TextBlob, kok kurang pas ya?
setau saya kan textblob untuk bhs Inggris, walaupun udh ditranslate hasilnya kok agak melenceng ya?

**Comment by ahtuz** [comment]
Iya benar sekali, mas Ian. Textblob memang untuk bahasa Inggris. Project ini sebenarnya lebih ke coba-coba atau eksperimen saya sih gimana hasilnya kalo di-translate aja. Jadi, mohon maaf karena saya reply-nya cukup lama (karena notification GitHub tidak muncul), dan mungkin cara kerja analisis tweet ini gak sesuai harapannya mas Ian. 

Terima kasih.

**Comment by IanNarsa** [comment]
Allhamdulillah, sebenernya saya jadi dapet refrensi baru ini, mungkin ini mas bisa kembangin untuk analisis sentimen dari suatu berita atau kalau di koran itu ada pojok opini.
Kenapa berita? karena penulisan berita itu tidak ada kalimat yang disngkat atau bisa dibilang mengikuti EYD sehingga klo ditranslate bisa lebih rapi dari pada yang murni komentar karena biasanya yg murni komentar itu mengandung singkatan yang hanya kita mengerti.

Terimakasih mas Ahtuz sudah membagikan kodingan ini, saya ijin untuk menjadikannya refrensi untuk praktik coba coba saya.


Best Regards
